#!/usr/bin/env python3
# guidance:generate-codex-artifacts@0.1.0
"""Generate Codex-local guidance artifacts from the canonical repo guidance."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
AGENTS_DIR = REPO_ROOT / "agents"
CODEX_DIR = REPO_ROOT / ".codex"
CODEX_AGENTS_DIR = CODEX_DIR / "agents"

SYMLINKS = {
    "skills": Path("../skills"),
    "commands": Path("../commands"),
}


@dataclass(frozen=True)
class AgentDoc:
    name: str
    description: str
    body: str


def _parse_agent(path: Path) -> AgentDoc:
    text = path.read_text()
    match = re.match(
        r"(?:<!--.*?-->\n)?---\n(?P<frontmatter>.*?)\n---\n(?P<body>.*)",
        text,
        flags=re.DOTALL,
    )
    if not match:
        raise ValueError(f"{path}: missing YAML frontmatter")

    frontmatter = match.group("frontmatter")
    body = match.group("body").strip() + "\n"
    name = _frontmatter_value(frontmatter, "name")
    description = _frontmatter_value(frontmatter, "description")
    return AgentDoc(name=name, description=description, body=body)


def _frontmatter_value(frontmatter: str, key: str) -> str:
    prefix = f"{key}:"
    for line in frontmatter.splitlines():
        if line.startswith(prefix):
            return line[len(prefix) :].strip()
    raise ValueError(f"frontmatter missing {key!r}")


def _toml_literal(value: str) -> str:
    if "'''" in value:
        raise ValueError("Codex agent text cannot contain TOML triple literal quotes")
    return "'''\n" + value + "'''"


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render_agent(agent: AgentDoc) -> str:
    return (
        "# Generated by templates/generate_codex_artifacts.py; do not edit.\n"
        f"name = {_toml_string(agent.name)}\n"
        f"description = {_toml_string(agent.description)}\n"
        f"developer_instructions = {_toml_literal(agent.body)}\n"
    )


def _expected_agent_files() -> dict[Path, str]:
    expected: dict[Path, str] = {}
    for path in sorted(AGENTS_DIR.glob("*.md")):
        agent = _parse_agent(path)
        expected[CODEX_AGENTS_DIR / f"{agent.name}.toml"] = _render_agent(agent)
    return expected


def _ensure_symlink(name: str, target: Path, *, check: bool) -> list[str]:
    link = CODEX_DIR / name
    if link.is_symlink() and link.readlink() == target:
        return []

    if check:
        return [f"{link}: expected symlink to {target}"]

    if link.exists() or link.is_symlink():
        if link.is_dir() and not link.is_symlink():
            raise IsADirectoryError(f"{link}: refusing to replace a real directory")
        link.unlink()
    link.symlink_to(target)
    return []


def _write_or_check(*, check: bool) -> list[str]:
    errors: list[str] = []
    CODEX_DIR.mkdir(exist_ok=True)

    for name, target in SYMLINKS.items():
        errors.extend(_ensure_symlink(name, target, check=check))

    expected = _expected_agent_files()
    actual_paths = set(CODEX_AGENTS_DIR.glob("*.toml")) if CODEX_AGENTS_DIR.exists() else set()

    if check:
        for path, expected_text in expected.items():
            if not path.exists():
                errors.append(f"{path}: missing")
                continue
            actual = path.read_text()
            if actual != expected_text:
                errors.append(f"{path}: stale generated content")
        for stale in sorted(actual_paths - set(expected)):
            errors.append(f"{stale}: stale generated file")
        return errors

    CODEX_AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    for stale in sorted(actual_paths - set(expected)):
        stale.unlink()
    for path, expected_text in expected.items():
        path.write_text(expected_text)
    return []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated artifacts are stale",
    )
    args = parser.parse_args(argv)

    errors = _write_or_check(check=args.check)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    if not args.check:
        print("codex artifacts: generated .codex agents, skills, and commands")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
