#!/usr/bin/env python3
# guidance:generate-codex-artifacts@0.2.0
"""Generate Codex-local guidance artifacts from the canonical repo guidance."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
AGENTS_DIR = REPO_ROOT / "agents"
COMMANDS_DIR = REPO_ROOT / "commands"
SKILLS_DIR = REPO_ROOT / "skills"
CODEX_DIR = REPO_ROOT / ".codex"
CODEX_AGENTS_DIR = CODEX_DIR / "agents"
CODEX_SKILLS_DIR = CODEX_DIR / "skills"
CODEX_COMMANDS = CODEX_DIR / "commands"


@dataclass(frozen=True)
class AgentDoc:
    name: str
    description: str
    body: str


def _parse_agent(path: Path) -> AgentDoc:
    text = path.read_text()
    match = re.match(
        r"(?:<!--.*?-->\n)?---\n(?P<frontmatter>.*?)\n---\n(?P<body>.*)",
        text,
        flags=re.DOTALL,
    )
    if not match:
        raise ValueError(f"{path}: missing YAML frontmatter")

    frontmatter = match.group("frontmatter")
    body = match.group("body").strip() + "\n"
    name = _frontmatter_value(frontmatter, "name")
    description = _frontmatter_value(frontmatter, "description")
    return AgentDoc(name=name, description=description, body=body)


def _frontmatter_value(frontmatter: str, key: str) -> str:
    prefix = f"{key}:"
    for line in frontmatter.splitlines():
        if line.startswith(prefix):
            return line[len(prefix) :].strip()
    raise ValueError(f"frontmatter missing {key!r}")


def _toml_literal(value: str) -> str:
    if "'''" in value:
        raise ValueError("Codex agent text cannot contain TOML triple literal quotes")
    return "'''\n" + value + "'''"


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render_agent(agent: AgentDoc) -> str:
    return (
        "# Generated by templates/generate_codex_artifacts.py; do not edit.\n"
        f"name = {_toml_string(agent.name)}\n"
        f"description = {_toml_string(agent.description)}\n"
        f"developer_instructions = {_toml_literal(agent.body)}\n"
    )


def _expected_agent_files() -> dict[Path, str]:
    expected: dict[Path, str] = {}
    for path in sorted(AGENTS_DIR.glob("*.md")):
        agent = _parse_agent(path)
        expected[CODEX_AGENTS_DIR / f"{agent.name}.toml"] = _render_agent(agent)
    return expected


def _ensure_symlink(link: Path, target: Path, *, check: bool) -> list[str]:
    if link.is_symlink() and link.readlink() == target:
        return []

    if check:
        return [f"{link}: expected symlink to {target}"]

    if link.exists() or link.is_symlink():
        if link.is_dir() and not link.is_symlink():
            raise IsADirectoryError(f"{link}: refusing to replace a real directory")
        link.unlink()
    link.symlink_to(target)
    return []


def _skill_ids() -> list[str]:
    return sorted(path.parent.name for path in SKILLS_DIR.glob("*/SKILL.md"))


def _command_skill_name(command: Path) -> str:
    slug = re.sub(r"[^a-z0-9-]+", "-", command.stem.lower()).strip("-")
    return f"command-{slug}"


def _command_invocations(command: Path) -> list[str]:
    if command.stem == "harness":
        return ["/harness", "/harness run", "/harness ingest", "/harness routine"]
    return [f"/{command.stem}"]


def _render_command_skill(command: Path) -> str:
    name = _command_skill_name(command)
    invocations = ", ".join(f"`{item}`" for item in _command_invocations(command))
    relative_command = command.relative_to(REPO_ROOT).as_posix()
    description = (
        f"Codex-native adapter for the repo command in `{relative_command}`. "
        f"Use when the user invokes {invocations} or asks to run that command workflow; "
        "read and follow the command file completely before acting."
    )
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        "---\n"
        f"# /{command.stem} Command\n\n"
        f"Read `{relative_command}` completely before taking action. Follow it as the "
        "canonical command contract for this request.\n\n"
        "This generated skill exists because Codex discovers repo-local skills, not "
        "repo-local slash commands. The canonical command remains the markdown file "
        "above; do not edit this adapter by hand.\n"
    )


def _expected_command_skills() -> dict[Path, str]:
    expected: dict[Path, str] = {}
    for command in sorted(COMMANDS_DIR.glob("*.md")):
        expected[CODEX_SKILLS_DIR / _command_skill_name(command) / "SKILL.md"] = (
            _render_command_skill(command)
        )
    return expected


def _ensure_codex_skills(*, check: bool) -> list[str]:
    errors: list[str] = []

    if CODEX_SKILLS_DIR.is_symlink() or (
        CODEX_SKILLS_DIR.exists() and not CODEX_SKILLS_DIR.is_dir()
    ):
        if check:
            return [f"{CODEX_SKILLS_DIR}: expected generated skills directory"]
        CODEX_SKILLS_DIR.unlink()

    if not check:
        CODEX_SKILLS_DIR.mkdir(parents=True, exist_ok=True)

    expected_skill_links = {
        CODEX_SKILLS_DIR / skill_id: Path("../../skills") / skill_id
        for skill_id in _skill_ids()
    }
    expected_command_skills = _expected_command_skills()

    if check and not CODEX_SKILLS_DIR.exists():
        errors.append(f"{CODEX_SKILLS_DIR}: missing")
        return errors

    for link, target in expected_skill_links.items():
        errors.extend(_ensure_symlink(link, target, check=check))

    actual_command_skill_dirs = (
        {path for path in CODEX_SKILLS_DIR.glob("command-*") if path.is_dir()}
        if CODEX_SKILLS_DIR.exists()
        else set()
    )
    expected_command_skill_dirs = {path.parent for path in expected_command_skills}

    if check:
        for path, expected_text in expected_command_skills.items():
            if not path.exists():
                errors.append(f"{path}: missing")
                continue
            if path.read_text() != expected_text:
                errors.append(f"{path}: stale generated content")
        for stale in sorted(actual_command_skill_dirs - expected_command_skill_dirs):
            errors.append(f"{stale}: stale generated command skill")
        return errors

    for stale in sorted(actual_command_skill_dirs - expected_command_skill_dirs):
        skill_file = stale / "SKILL.md"
        if skill_file.exists():
            skill_file.unlink()
        stale.rmdir()
    for path, expected_text in expected_command_skills.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected_text)
    return errors


def _remove_unsupported_codex_commands(*, check: bool) -> list[str]:
    if not CODEX_COMMANDS.exists() and not CODEX_COMMANDS.is_symlink():
        return []
    if check:
        return [f"{CODEX_COMMANDS}: Codex does not discover repo-local slash commands"]
    if CODEX_COMMANDS.is_dir() and not CODEX_COMMANDS.is_symlink():
        raise IsADirectoryError(f"{CODEX_COMMANDS}: refusing to remove a real directory")
    CODEX_COMMANDS.unlink()
    return []


def _write_or_check(*, check: bool) -> list[str]:
    errors: list[str] = []
    CODEX_DIR.mkdir(exist_ok=True)

    errors.extend(_ensure_codex_skills(check=check))
    errors.extend(_remove_unsupported_codex_commands(check=check))

    expected = _expected_agent_files()
    actual_paths = set(CODEX_AGENTS_DIR.glob("*.toml")) if CODEX_AGENTS_DIR.exists() else set()

    if check:
        for path, expected_text in expected.items():
            if not path.exists():
                errors.append(f"{path}: missing")
                continue
            actual = path.read_text()
            if actual != expected_text:
                errors.append(f"{path}: stale generated content")
        for stale in sorted(actual_paths - set(expected)):
            errors.append(f"{stale}: stale generated file")
        return errors

    CODEX_AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    for stale in sorted(actual_paths - set(expected)):
        stale.unlink()
    for path, expected_text in expected.items():
        path.write_text(expected_text)
    return []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated artifacts are stale",
    )
    args = parser.parse_args(argv)

    errors = _write_or_check(check=args.check)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    if not args.check:
        print("codex artifacts: generated .codex agents and skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
