#!/usr/bin/env python3
"""Compile the native and repo-local Codex surfaces (ADR 0017).

Emits portable command/agent skills, ``AGENTS.md``, current ``.agents/skills``
links, and legacy-compatible ``.codex`` agents and skills. Outputs are committed;
``--check`` compares them with a regeneration so drift makes the gate red.
"""

# size: this file is the one compiler boundary for five mutually checked output
# families; splitting a writer away from its shared inventory would duplicate it.

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

_GENERATOR = "scripts/generate_codex_artifacts.py"
_PORTABLE_ROOT_NOTE = (
    "The portable plugin root is two directories above this SKILL.md. Resolve embedded "
    "paths beginning `commands/`, `skills/`, `agents/`, `templates/`, `hooks/`, or "
    "`.codex/` from that root; resolve repository artifacts from the workspace root."
)
_LEGACY_ROOT_NOTE = (
    "The plugin root is three directories above this SKILL.md in this legacy `.codex` "
    "layout. Resolve embedded paths beginning `commands/`, `skills/`, `agents/`, "
    "`templates/`, `hooks/`, or `.codex/` from that root; resolve repository artifacts "
    "from the workspace root."
)

_FRONTMATTER_RE = re.compile(
    r"(?:<!--.*?-->\n)?---\n(?P<frontmatter>.*?)\n---\n(?P<body>.*)",
    flags=re.DOTALL,
)


@dataclass(frozen=True)
class Layout:
    """Every path the compile reads or writes, hung off one root.

    Parameterised so the tests can run the generator against fixture repos; the
    default root is this repository.
    """

    root: Path

    @property
    def spine(self) -> Path:
        return self.root / "CLAUDE.md"

    @property
    def agents_md(self) -> Path:
        return self.root / "AGENTS.md"

    @property
    def agents_dir(self) -> Path:
        return self.root / "agents"

    @property
    def commands_dir(self) -> Path:
        return self.root / "commands"

    @property
    def skills_dir(self) -> Path:
        return self.root / "skills"

    @property
    def codex_dir(self) -> Path:
        return self.root / ".codex"

    @property
    def codex_agents_dir(self) -> Path:
        return self.codex_dir / "agents"

    @property
    def codex_skills_dir(self) -> Path:
        return self.codex_dir / "skills"

    @property
    def codex_commands(self) -> Path:
        return self.codex_dir / "commands"

    @property
    def agents_skills_dir(self) -> Path:
        return self.root / ".agents" / "skills"


@dataclass(frozen=True)
class AgentDoc:
    name: str
    description: str
    body: str


def _parse_frontmatter(path: Path) -> tuple[str, str]:
    """``(frontmatter, body)`` of a markdown file, or a named failure."""
    match = _FRONTMATTER_RE.match(path.read_text(encoding="utf-8"))
    if not match:
        raise ValueError(f"{path}: missing YAML frontmatter")
    return match.group("frontmatter"), match.group("body")


def _frontmatter_value(frontmatter: str, key: str, *, source: Path) -> str:
    prefix = f"{key}:"
    for line in frontmatter.splitlines():
        if line.startswith(prefix):
            return line[len(prefix) :].strip()
    raise ValueError(f"{source}: frontmatter missing {key!r}")


def _parse_agent(path: Path) -> AgentDoc:
    frontmatter, body = _parse_frontmatter(path)
    return AgentDoc(
        name=_frontmatter_value(frontmatter, "name", source=path),
        description=_frontmatter_value(frontmatter, "description", source=path),
        body=body.strip() + "\n",
    )


def _toml_literal(value: str) -> str:
    if "'''" in value:
        raise ValueError("Codex agent text cannot contain TOML triple literal quotes")
    return "'''\n" + value + "'''"


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render_agent(agent: AgentDoc) -> str:
    return (
        f"# Generated by {_GENERATOR}; do not edit.\n"
        f"name = {_toml_string(agent.name)}\n"
        f"description = {_toml_string(agent.description)}\n"
        f"developer_instructions = {_toml_literal(agent.body)}\n"
    )


def _expected_agent_files(layout: Layout) -> dict[Path, str]:
    expected: dict[Path, str] = {}
    for path in sorted(layout.agents_dir.glob("*.md")):
        agent = _parse_agent(path)
        expected[layout.codex_agents_dir / f"{agent.name}.toml"] = _render_agent(agent)
    return expected


def _command_heading(path: Path) -> tuple[str, str]:
    """``(/name, description)`` from the command's ``# /name — description``.

    The heading is the first ``# `` line, not necessarily the first line: two
    commands open with a tracker-dispatch preamble paragraph.
    """
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            name, sep, description = line[2:].strip().partition(" — ")
            if not sep or not name.startswith("/") or not description.strip():
                raise ValueError(
                    f"{path}: command heading must be '# /name — description'; got {line!r}"
                )
            return name.strip(), description.strip()
    raise ValueError(f"{path}: no '# ' heading found")


def _skill_entry(path: Path) -> tuple[str, str]:
    frontmatter, _ = _parse_frontmatter(path)
    return (
        _frontmatter_value(frontmatter, "name", source=path),
        _frontmatter_value(frontmatter, "description", source=path),
    )


def _render_agents_md(layout: Layout) -> str:
    """The compiled ``AGENTS.md``: the spine, then the generated index."""
    lines: list[str] = [
        f"<!-- Generated by {_GENERATOR} from CLAUDE.md and the guidance",
        "     inventory; do not edit. Regenerate with:",
        f"     uv run python {_GENERATOR} -->",
        "",
        layout.spine.read_text(encoding="utf-8").rstrip(),
        "",
        "## Guidance index (generated)",
        "",
        "Codex reads this file natively but discovers none of the leaves on its",
        "own. Each entry points at the canonical file; read it before acting on",
        "the workflow it names.",
        "",
        "### Commands",
        "",
    ]
    for command in sorted(layout.commands_dir.glob("*.md")):
        name, description = _command_heading(command)
        rel = command.relative_to(layout.root).as_posix()
        lines.append(f"- `{name}` — {description} (`{rel}`)")
    lines += ["", "### Skills", ""]
    for skill_md in sorted(layout.skills_dir.glob("*/SKILL.md")):
        name, description = _skill_entry(skill_md)
        rel = skill_md.relative_to(layout.root).as_posix()
        lines.append(f"- **{name}** — {description} (`{rel}`)")
    return "\n".join(lines) + "\n"


def _ensure_agents_md(layout: Layout, *, check: bool) -> list[str]:
    expected = _render_agents_md(layout)
    if check:
        if not layout.agents_md.is_file():
            return [f"{layout.agents_md}: missing — run `python {_GENERATOR}`"]
        if layout.agents_md.read_text(encoding="utf-8") != expected:
            return [
                f"{layout.agents_md}: stale — does not match a regeneration; "
                f"run `python {_GENERATOR}`"
            ]
        return []
    layout.agents_md.write_text(expected, encoding="utf-8")
    return []


def _ensure_symlink(link: Path, target: Path, *, check: bool) -> list[str]:
    if link.is_symlink() and link.readlink() == target:
        return []

    if check:
        return [f"{link}: expected symlink to {target}"]

    if link.exists() or link.is_symlink():
        if link.is_dir() and not link.is_symlink():
            raise IsADirectoryError(f"{link}: refusing to replace a real directory")
        link.unlink()
    link.symlink_to(target)
    return []


def _skill_ids(layout: Layout) -> list[str]:
    return sorted(path.parent.name for path in layout.skills_dir.glob("*/SKILL.md"))


def _command_skill_name(command: Path) -> str:
    slug = re.sub(r"[^a-z0-9-]+", "-", command.stem.lower()).strip("-")
    return f"command-{slug}"


def _render_command_skill(layout: Layout, command: Path, *, root_note: str) -> str:
    name = _command_skill_name(command)
    invocation, description = _command_heading(command)
    relative_command = command.relative_to(layout.root).as_posix()
    skill_description = (
        f"Codex-native adapter for the repo command in `{relative_command}` "
        f"({description}). Use when the user invokes `{invocation}` or asks to run "
        "that command workflow; read and follow the command file completely before acting."
    )
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {_toml_string(skill_description)}\n"
        "---\n"
        f"<!-- Generated by {_GENERATOR}; do not edit. -->\n"
        f"{root_note}\n\n"
        f"# {invocation} Command\n\n"
        "The following is the complete command contract, embedded so this skill remains "
        "portable when the plugin is installed into a host cache.\n\n"
        + command.read_text(encoding="utf-8").strip()
        + "\n"
    )


def _expected_command_skills(layout: Layout) -> dict[Path, str]:
    expected: dict[Path, str] = {}
    for command in sorted(layout.commands_dir.glob("*.md")):
        expected[layout.codex_skills_dir / _command_skill_name(command) / "SKILL.md"] = (
            _render_command_skill(layout, command, root_note=_LEGACY_ROOT_NOTE)
        )
    return expected


def _expected_portable_skills(layout: Layout) -> dict[Path, str]:
    expected = {
        layout.skills_dir / _command_skill_name(command) / "SKILL.md": (
            _render_command_skill(layout, command, root_note=_PORTABLE_ROOT_NOTE)
        )
        for command in sorted(layout.commands_dir.glob("*.md"))
    }
    for agent_path in sorted(layout.agents_dir.glob("*.md")):
        agent = _parse_agent(agent_path)
        role_description = agent.description + " Use when acting in or delegating to this role."
        path = layout.skills_dir / f"agent-{agent.name}" / "SKILL.md"
        expected[path] = (
            "---\n"
            f"name: agent-{agent.name}\n"
            f"description: {_toml_string(role_description)}\n"
            "---\n"
            f"<!-- Generated by {_GENERATOR}; do not edit. -->\n"
            f"{_PORTABLE_ROOT_NOTE}\n\n"
            f"# {agent.name.title()} Role\n\n"
            f"{agent.body}"
        )
    return expected


def _ensure_portable_skills(layout: Layout, *, check: bool) -> list[str]:
    errors: list[str] = []
    expected = _expected_portable_skills(layout)
    generated_dirs = {
        path.parent
        for prefix in ("command-*", "agent-*")
        for path in layout.skills_dir.glob(f"{prefix}/SKILL.md")
        if f"<!-- Generated by {_GENERATOR}; do not edit. -->" in path.read_text(encoding="utf-8")
    }
    expected_dirs = {path.parent for path in expected}
    if check:
        for path, text in expected.items():
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                errors.append(f"{path}: missing or stale generated portable skill")
        for stale in sorted(generated_dirs - expected_dirs):
            errors.append(f"{stale}: stale generated portable skill")
        return errors

    for stale in sorted(generated_dirs - expected_dirs):
        (stale / "SKILL.md").unlink()
        stale.rmdir()
    for path, text in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return errors


def _ensure_official_skill_links(layout: Layout, *, check: bool) -> list[str]:
    errors: list[str] = []
    skills_dir = layout.agents_skills_dir
    expected = {
        skills_dir / skill_id: Path("../../skills") / skill_id
        for skill_id in _skill_ids(layout)
    }
    if not check:
        skills_dir.mkdir(parents=True, exist_ok=True)
    if check and not skills_dir.is_dir():
        return [f"{skills_dir}: missing"]
    for link, target in expected.items():
        errors.extend(_ensure_symlink(link, target, check=check))
    actual: set[Path] = set()
    if skills_dir.exists():
        actual = {path for path in skills_dir.iterdir() if path.is_symlink()}
    if check:
        stale = sorted(actual - set(expected))
        errors.extend(f"{path}: stale generated skill symlink" for path in stale)
    else:
        for path in sorted(actual - set(expected)):
            path.unlink()
    return errors


def _ensure_codex_skills(layout: Layout, *, check: bool) -> list[str]:
    errors: list[str] = []
    skills_dir = layout.codex_skills_dir

    if skills_dir.is_symlink() or (skills_dir.exists() and not skills_dir.is_dir()):
        if check:
            return [f"{skills_dir}: expected generated skills directory"]
        skills_dir.unlink()

    if not check:
        skills_dir.mkdir(parents=True, exist_ok=True)

    expected_command_skills = _expected_command_skills(layout)
    command_skill_ids = {path.parent.name for path in expected_command_skills}
    expected_skill_links = {
        skills_dir / skill_id: Path("../../skills") / skill_id
        for skill_id in _skill_ids(layout)
        if skill_id not in command_skill_ids
    }

    if check and not skills_dir.exists():
        errors.append(f"{skills_dir}: missing")
        return errors

    for link, target in expected_skill_links.items():
        errors.extend(_ensure_symlink(link, target, check=check))

    # A retired skill leaves its generated symlink behind. Nothing else notices:
    # the link still parses, `--check` only inspects the links it expects, and
    # Codex resolves it to a directory that no longer exists. So prune every
    # symlink under the generated skills dir that no canonical skill claims.
    stale_skill_links = (
        {
            path
            for path in skills_dir.iterdir()
            if path.is_symlink() and path not in expected_skill_links
        }
        if skills_dir.exists()
        else set()
    )
    if check:
        for stale_link in sorted(stale_skill_links):
            errors.append(f"{stale_link}: stale generated skill symlink")
    else:
        for stale_link in sorted(stale_skill_links):
            stale_link.unlink()

    actual_command_skill_dirs = (
        {path for path in skills_dir.glob("command-*") if path.is_dir()}
        if skills_dir.exists()
        else set()
    )
    expected_command_skill_dirs = {path.parent for path in expected_command_skills}

    if check:
        for path, expected_text in expected_command_skills.items():
            if not path.exists():
                errors.append(f"{path}: missing")
                continue
            if path.read_text(encoding="utf-8") != expected_text:
                errors.append(f"{path}: stale generated content")
        for stale in sorted(actual_command_skill_dirs - expected_command_skill_dirs):
            errors.append(f"{stale}: stale generated command skill")
        return errors

    for stale in sorted(actual_command_skill_dirs - expected_command_skill_dirs):
        skill_file = stale / "SKILL.md"
        if skill_file.exists():
            skill_file.unlink()
        stale.rmdir()
    for path, expected_text in expected_command_skills.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected_text, encoding="utf-8")
    return errors


def _remove_unsupported_codex_commands(layout: Layout, *, check: bool) -> list[str]:
    commands = layout.codex_commands
    if not commands.exists() and not commands.is_symlink():
        return []
    if check:
        return [f"{commands}: Codex does not discover repo-local slash commands"]
    if commands.is_dir() and not commands.is_symlink():
        raise IsADirectoryError(f"{commands}: refusing to remove a real directory")
    commands.unlink()
    return []


def _write_or_check(layout: Layout, *, check: bool) -> list[str]:
    errors: list[str] = []
    errors.extend(_ensure_portable_skills(layout, check=check))
    if check and errors:
        return errors
    errors.extend(_ensure_agents_md(layout, check=check))

    if check:
        if not layout.codex_dir.is_dir():
            errors.append(f"{layout.codex_dir}: missing")
            return errors
    else:
        layout.codex_dir.mkdir(exist_ok=True)

    errors.extend(_ensure_codex_skills(layout, check=check))
    errors.extend(_ensure_official_skill_links(layout, check=check))
    errors.extend(_remove_unsupported_codex_commands(layout, check=check))

    expected = _expected_agent_files(layout)
    actual_paths = (
        set(layout.codex_agents_dir.glob("*.toml"))
        if layout.codex_agents_dir.exists()
        else set()
    )

    if check:
        for path, expected_text in expected.items():
            if not path.exists():
                errors.append(f"{path}: missing")
                continue
            if path.read_text(encoding="utf-8") != expected_text:
                errors.append(f"{path}: stale generated content")
        for stale in sorted(actual_paths - set(expected)):
            errors.append(f"{stale}: stale generated file")
        return errors

    layout.codex_agents_dir.mkdir(parents=True, exist_ok=True)
    for stale in sorted(actual_paths - set(expected)):
        stale.unlink()
    for path, expected_text in expected.items():
        path.write_text(expected_text, encoding="utf-8")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated artifacts are stale, writing nothing",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="repository root to compile (default: this repository)",
    )
    args = parser.parse_args(argv)
    layout = Layout(root=args.root.resolve())

    errors = _write_or_check(layout, check=args.check)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    if args.check:
        print(
            "codex drift guard: OK — AGENTS.md, portable skills, .agents/, and "
            f".codex/ match {_GENERATOR}"
        )
    else:
        print("codex artifacts: generated native skills, AGENTS.md, .agents/, and .codex/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
