"""#537 — the two copies of each role's guidance still correspond.

``agents/<name>.md`` is the role definition Claude Code dispatches;
``.codex/agents/<name>.toml`` is Codex's native adapter for the same role, and
``/harness:init`` copies it into a consuming repo. The two carry the same body in
two file formats, so they are a mirror pair.

**Why this exists at all.** Until #537 that pair was generated by
``scripts/generate_codex_artifacts.py``, whose ``--check`` ran as a gate stage —
375 lines of generator, a stage, and a test module, holding four mirror sets in
step. Three of those four sets are gone: the nine ``command-*`` skills and the
nine ``commands/*.md`` files collapsed into nine skills, the four ``agent-*``
skill mirrors were the third copy of this same body and were deleted, and
``AGENTS.md`` is authored now. This pair is what is left, and deleting the
generator without replacing its check for the survivor would have retired the
guard along with the thing it guarded — trading a real protection for a line
count. So: one guard, one pair, no generator.

**Admitted under ADR 0017 D5 class (e), tree-consistency.** Both operands are
tracked documents and the assertion is that a region of each *corresponds*. The
body is compared as an opaque string; nothing here reads what any sentence means,
so a reword applied to both files passes and a reword applied to one fails.

**Emptiness is refused, on both operands.** ``craft.md`` → the
identically-failed-renders class (#466), and *floor both measured operands*
(#486): two extractions that both failed compare equal, and ``"" == ""`` is the
one comparison a correspondence guard must never make. A missing delimiter, an
unterminated block, or a well-formed but empty body raises here rather than
yielding ``""``.

**The tracked tree, not the working one.** Both operands are read through
``indexed_text``: a guard over the working directory passes on bytes that are not
the bytes that ship.
"""

from __future__ import annotations

import pytest

from tests._gitutil import indexed_text, tracked_files_under

#: The delimiter Codex's TOML uses for the role body. A literal multi-line string,
#: so nothing inside it is escaped and the comparison is byte-for-byte.
FENCE = "'''"

ROLES = sorted(path.stem for path in tracked_files_under("agents") if path.suffix == ".md")

#: The adapters git actually tracks, by role name.
ADAPTERS = {path.stem for path in tracked_files_under(".codex/agents") if path.suffix == ".toml"}


def _markdown_body(role: str) -> str:
    """The role's guidance, with its YAML frontmatter removed."""
    text = indexed_text(f"agents/{role}.md")
    assert text.startswith("---\n"), f"agents/{role}.md carries no frontmatter"
    end = text.index("\n---\n", 3)
    body = text[end + len("\n---\n") :].strip()
    assert body, f"agents/{role}.md has an empty body, which compares equal to anything"
    return body


def _toml_body(role: str) -> str:
    """The role's guidance out of ``developer_instructions``."""
    text = indexed_text(f".codex/agents/{role}.toml")
    key = "developer_instructions = " + FENCE
    assert key in text, f".codex/agents/{role}.toml declares no developer_instructions block"
    start = text.index(key) + len(key)
    assert FENCE in text[start:], f".codex/agents/{role}.toml's body block is unterminated"
    body = text[start : start + text[start:].index(FENCE)].strip()
    assert body, f".codex/agents/{role}.toml has an empty body, which compares equal to anything"
    return body


def test_there_are_roles_to_compare() -> None:
    """The floor under the parametrisation. Without it, deleting every role file
    turns the sweep below into a vacuous pass over an empty list."""
    assert len(ROLES) >= 4, f"expected the four shipped roles, found {ROLES}"


@pytest.mark.parametrize("role", ROLES)
def test_each_role_ships_a_codex_adapter(role: str) -> None:
    """A role Claude Code can dispatch and Codex cannot is a silent host gap: the
    Codex session simply has no such agent, and nothing says so."""
    assert role in ADAPTERS, (
        f"agents/{role}.md has no Codex adapter, so that role does not exist on Codex"
    )


@pytest.mark.parametrize("role", ROLES)
def test_both_copies_of_a_role_carry_the_same_body(role: str) -> None:
    assert _markdown_body(role) == _toml_body(role), (
        f"agents/{role}.md and .codex/agents/{role}.toml have drifted, so the two "
        "hosts dispatch the same role with different instructions"
    )


@pytest.mark.parametrize("role", ROLES)
def test_both_copies_of_a_role_carry_the_same_description(role: str) -> None:
    """The description is what selects the role, so drift here is drift in *which*
    agent gets dispatched, not only in what it then reads."""
    markdown = indexed_text(f"agents/{role}.md")
    line = next(ln for ln in markdown.splitlines() if ln.startswith("description:"))
    expected = line.split(":", 1)[1].strip().strip('"')
    toml = indexed_text(f".codex/agents/{role}.toml")
    declared = next(ln for ln in toml.splitlines() if ln.startswith("description = "))
    assert declared.split("=", 1)[1].strip().strip('"') == expected, (
        f"{role}'s description differs between the two hosts"
    )
